version: '3.7'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: ${PROJECT_NAME}_GITLAB
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${DOMAIN}.traefik.me'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
    ports:
      - '2224:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_GITLAB.rule=Host(`${DOMAIN}.traefik.me`)"
      - "traefik.http.services.${PROJECT_NAME}_GITLAB.loadbalancer.server.port=80"
      - "traefik.http.routers.${PROJECT_NAME}_GITLAB.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}_GITLAB.tls.domains[0].main=${DOMAIN}.traefik.me"
      - "traefik.http.routers.${PROJECT_NAME}_GITLAB.tls.domains[0].sans=*.${DOMAIN}.traefik.me"
    networks:
      default:


  gitlab_runner:
    image: gitlab/gitlab-runner:latest
    container_name: ${PROJECT_NAME}_RUNNER
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner:/etc/gitlab-runner
    depends_on:
      - gitlab
    networks:
      default:
  busybox:
    image: busybox:latest
    container_name: ${PROJECT_NAME}_BUSYBOX
    restart: always
    command: sh -c "while true; do sleep 3600; done"
    networks:
      default:


networks:
  default:
    name: ${NETWORK_NAME}
volumes:
  gitlab-config:
    name: ${PROJECT_NAME}_15gitlab-config
  gitlab-logs:
    name: ${PROJECT_NAME}_15gitlab-logs
  gitlab-data:
    name: ${PROJECT_NAME}_15gitlab-data
  gitlab-runner:
    name: ${PROJECT_NAME}_15gitlab-runner
